### ISSUE TITLE
Overlay demo don't work on chrome

### ISSUE THREAD

**Issue by Sky84** [haliphax/hxavatars#1]
![image](https://user-images.githubusercontent.com/12623083/160479124-9c5a05f2-3fb6-4640-8c55-b8bfc0a81fc5.png)

I just don't have avatars on the overlay demo on chrome

**Comment by haliphax** [comment]
Hit F11 for full screen and see if it helps?

**Comment by Sky84** [comment]
Yup, thks. With F11 it works...
